package main;

public enum QuantityType {
	//Mass
	GRAMS, KILOGRAMS, OUNCES, POUNDS, 
	
	//Volume
	MILLILITRES, LITRES, PINTS, GALLONS,
	DROPS, SMIDGENS, PINCHES, DASHES, SALTSPOONS, SCRUPLES, COFFEESPOONS, DRAMS, TEASPOONS, DESSERTSPOONS, TABLESPOONS, FLUIDOUNCES, WINEGLASSES, TEACUPS, GILLS, CUP, QUART, POTTLE,
	
	//Quantity
	WHOLE, OTHER
	
}
